### ISSUE TITLE
	API REFRESH TOKEN ERROR: login_required: undefined

### ISSUE THREAD

**Issue by Klaus-Lucas** [iobroker-community-adapters/ioBroker.wolf-smartset#295]
Habe ein ISM7 und einen Account für die Wolf Cloud, wo ich mein Gerät registriert habe.
![klu_002](https://github.com/iobroker-community-adapters/ioBroker.wolf-smartset/assets/36620907/f3b4da62-b52e-406d-bccc-e1f246b8b725)

Wie schon in #286 diskutiert, kann nur die Adapterversion 1.0.0 das Gerät aus der Cloud auslesen.
Daher musste ich erst die Version 1.1.1 installieren, um dann die 1.0.0 auswählen und installieren zu können.

![klu_012](https://github.com/iobroker-community-adapters/ioBroker.wolf-smartset/assets/36620907/3b1c6aea-b1a6-444b-bb95-7b4c93f81cc3)

![klu_013](https://github.com/iobroker-community-adapters/ioBroker.wolf-smartset/assets/36620907/c23a1369-98f5-4676-b4bc-352a851f0c02)

In die 1.0.0 habe ich meine Credentials eingetragen und konnte meine Device übernehmen.
Danach habe ich die 1.1.1 wieder installiert.
![klu_006](https://github.com/iobroker-community-adapters/ioBroker.wolf-smartset/assets/36620907/ca8e5485-e6df-4d6e-9dd1-9788f43d790b)

![klu_001](https://github.com/iobroker-community-adapters/ioBroker.wolf-smartset/assets/36620907/afe60f17-374d-48f4-a77b-0ec3e946039d)

Nach dem Start des Adapters tauchten diese Meldungen auf:
2023-10-20 13:04:52.795 - warn: wolf-smartset.0 (314534) API REFRESH TOKEN ERROR: login_required: undefined
2023-10-20 13:04:52.797 - warn: wolf-smartset.0 (314534) Error: login_required: undefined

Log:
2023-10-20 13:02:24.692 - info: host.iobroker iobroker add wolf-smartset auto --host iobroker --debug
2023-10-20 13:02:25.301 - info: host.iobroker iobroker NPM version: 10.2.0
2023-10-20 13:02:25.302 - info: host.iobroker iobroker Installing iobroker.wolf-smartset@1.1.1... (System call)
2023-10-20 13:02:27.288 - info: host.iobroker iobroker added 5 packages in 2s243 packages are looking for funding
2023-10-20 13:02:27.288 - info: host.iobroker iobroker run `npm fund` for details
2023-10-20 13:02:27.296 - info: host.iobroker iobroker host.iobroker install adapter wolf-smartset
2023-10-20 13:02:27.315 - info: host.iobroker iobroker upload [4] wolf-smartset.admin /opt/iobroker/node_modules/iobroker.wolf-smartset/admin/admin.d.ts admin.d.ts video/mp2t
2023-10-20 13:02:27.319 - info: host.iobroker iobroker upload [3] wolf-smartset.admin /opt/iobroker/node_modules/iobroker.wolf-smartset/admin/index_m.html index_m.html text/html
2023-10-20 13:02:27.321 - info: host.iobroker iobroker upload [2] wolf-smartset.admin /opt/iobroker/node_modules/iobroker.wolf-smartset/admin/style.css style.css text/css
2023-10-20 13:02:27.322 - info: host.iobroker iobroker upload [1] wolf-smartset.admin /opt/iobroker/node_modules/iobroker.wolf-smartset/admin/wolf-smartset.png wolf-smartset.png image/png
2023-10-20 13:02:27.323 - info: host.iobroker iobroker upload [0] wolf-smartset.admin /opt/iobroker/node_modules/iobroker.wolf-smartset/admin/words.js words.js application/javascript
2023-10-20 13:02:27.350 - info: host.iobroker iobroker host.iobroker object system.adapter.wolf-smartset created/updated
2023-10-20 13:02:27.373 - info: host.iobroker iobroker host.iobroker create instance wolf-smartset
2023-10-20 13:02:27.375 - info: host.iobroker iobroker host.iobroker object system.adapter.wolf-smartset.0.alive created
2023-10-20 13:02:27.377 - info: host.iobroker iobroker host.iobroker object system.adapter.wolf-smartset.0.connected created
2023-10-20 13:02:27.379 - info: host.iobroker iobroker host.iobroker object system.adapter.wolf-smartset.0.compactMode created
2023-10-20 13:02:27.381 - info: host.iobroker iobroker host.iobroker object system.adapter.wolf-smartset.0.cpu created
2023-10-20 13:02:27.382 - info: host.iobroker iobroker host.iobroker object system.adapter.wolf-smartset.0.cputime created
2023-10-20 13:02:27.384 - info: host.iobroker iobroker host.iobroker object system.adapter.wolf-smartset.0.memHeapUsed created
2023-10-20 13:02:27.385 - info: host.iobroker iobroker host.iobroker object system.adapter.wolf-smartset.0.memHeapTotal created
2023-10-20 13:02:27.387 - info: host.iobroker iobroker host.iobroker object system.adapter.wolf-smartset.0.memRss created
2023-10-20 13:02:27.388 - info: host.iobroker iobroker host.iobroker object system.adapter.wolf-smartset.0.uptime created
2023-10-20 13:02:27.389 - info: host.iobroker iobroker host.iobroker object system.adapter.wolf-smartset.0.inputCount created
2023-10-20 13:02:27.390 - info: host.iobroker iobroker host.iobroker object system.adapter.wolf-smartset.0.outputCount created
2023-10-20 13:02:27.391 - info: host.iobroker iobroker host.iobroker object system.adapter.wolf-smartset.0.eventLoopLag created
2023-10-20 13:02:27.393 - info: host.iobroker iobroker host.iobroker object system.adapter.wolf-smartset.0.sigKill created
2023-10-20 13:02:27.395 - info: host.iobroker iobroker host.iobroker object system.adapter.wolf-smartset.0.logLevel created
2023-10-20 13:02:27.396 - info: host.iobroker iobroker host.iobroker object wolf-smartset.0.info created
2023-10-20 13:02:27.397 - info: host.iobroker iobroker host.iobroker object wolf-smartset.0.info.connection created
2023-10-20 13:02:27.398 - info: host.iobroker iobroker host.iobroker Set default value of wolf-smartset.0.info.connection: false
2023-10-20 13:02:27.400 - info: host.iobroker iobroker host.iobroker object system.adapter.wolf-smartset.0 created
2023-10-20 13:02:28.408 - info: host.iobroker iobroker exit 0

2023-10-20 13:02:30.430 - info: host.iobroker instance system.adapter.wolf-smartset.0 started with pid 314183
2023-10-20 13:02:30.837 - error: wolf-smartset.0 (314183) Please configure user, password and device in config
2023-10-20 13:02:30.891 - error: wolf-smartset.0 (314183) SyntaxError: Unexpected token u in JSON at position 0
at JSON.parse ()
at WolfSmartset.onReady (/opt/iobroker/node_modules/iobroker.wolf-smartset/main.js:37:18)
at WolfSmartset.emit (node:events:514:28)
at WolfSmartset.emit (node:domain:489:12)
at WolfSmartset._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11888:18)
at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11865:26
2023-10-20 13:03:04.437 - warn: wolf-smartset.0 (314183) API GET AUTH TOKEN ERROR: Cannot read properties of undefined (reading 'authorizationUrl')
2023-10-20 13:03:04.454 - warn: wolf-smartset.0 (314183) TypeError: Cannot read properties of undefined (reading 'authorizationUrl')
at WolfSmartSet._getAuthToken (/opt/iobroker/node_modules/iobroker.wolf-smartset/lib/wss.js:167:38)
at WolfSmartSet.adminGetDevicelist (/opt/iobroker/node_modules/iobroker.wolf-smartset/lib/wss.js:134:32)
at WolfSmartset.onMessage (/opt/iobroker/node_modules/iobroker.wolf-smartset/main.js:430:34)
at WolfSmartset.emit (node:events:514:28)
at WolfSmartset.emit (node:domain:489:12)
at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11100:34)
at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:379:37)
at processImmediate (node:internal/timers:476:21)
2023-10-20 13:03:11.685 - info: host.iobroker stopInstance system.adapter.wolf-smartset.0 (force=false, process=true)
2023-10-20 13:03:11.737 - info: host.iobroker stopInstance system.adapter.wolf-smartset.0 send kill signal
2023-10-20 13:03:12.214 - info: host.iobroker instance system.adapter.wolf-smartset.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2023-10-20 13:03:14.766 - info: host.iobroker instance system.adapter.wolf-smartset.0 started with pid 314198
2023-10-20 13:03:15.179 - error: wolf-smartset.0 (314198) Please configure user, password and device in config
2023-10-20 13:03:15.232 - error: wolf-smartset.0 (314198) TypeError: Cannot read properties of null (reading 'Id')
at WolfSmartset.onReady (/opt/iobroker/node_modules/iobroker.wolf-smartset/main.js:40:23)
at WolfSmartset.emit (node:events:514:28)
at WolfSmartset.emit (node:domain:489:12)
at WolfSmartset._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11888:18)
at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11865:26
2023-10-20 13:03:17.683 - warn: wolf-smartset.0 (314198) API GET AUTH TOKEN ERROR: Cannot read properties of undefined (reading 'authorizationUrl')
2023-10-20 13:03:17.694 - warn: wolf-smartset.0 (314198) TypeError: Cannot read properties of undefined (reading 'authorizationUrl')
at WolfSmartSet._getAuthToken (/opt/iobroker/node_modules/iobroker.wolf-smartset/lib/wss.js:167:38)
at WolfSmartSet.adminGetDevicelist (/opt/iobroker/node_modules/iobroker.wolf-smartset/lib/wss.js:134:32)
at WolfSmartset.onMessage (/opt/iobroker/node_modules/iobroker.wolf-smartset/main.js:430:34)
at WolfSmartset.emit (node:events:514:28)
at WolfSmartset.emit (node:domain:489:12)
at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11100:34)
at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:379:37)
at processImmediate (node:internal/timers:476:21)
2023-10-20 13:03:19.517 - warn: wolf-smartset.0 (314198) API GET AUTH TOKEN ERROR: Cannot read properties of undefined (reading 'authorizationUrl')
2023-10-20 13:03:19.517 - warn: wolf-smartset.0 (314198) TypeError: Cannot read properties of undefined (reading 'authorizationUrl')
at WolfSmartSet._getAuthToken (/opt/iobroker/node_modules/iobroker.wolf-smartset/lib/wss.js:167:38)
at WolfSmartSet.adminGetDevicelist (/opt/iobroker/node_modules/iobroker.wolf-smartset/lib/wss.js:134:32)
at WolfSmartset.onMessage (/opt/iobroker/node_modules/iobroker.wolf-smartset/main.js:430:34)
at WolfSmartset.emit (node:events:514:28)
at WolfSmartset.emit (node:domain:489:12)
at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11100:34)
at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:379:37)
at processImmediate (node:internal/timers:476:21)

2023-10-20 13:03:40.950 - info: host.iobroker iobroker upgrade wolf-smartset@1.0.0 --debug
2023-10-20 13:03:41.413 - info: host.iobroker iobroker Update wolf-smartset from @1.1.1 to @1.0.0
2023-10-20 13:03:41.564 - info: host.iobroker iobroker NPM version: 10.2.0
2023-10-20 13:03:41.565 - info: host.iobroker iobroker Installing iobroker.wolf-smartset@1.0.0... (System call)
2023-10-20 13:03:42.768 - info: host.iobroker iobroker added 1 package, removed 3 packages, and changed 1 package in 1s241 packages are looking for funding run `npm fund` for details
2023-10-20 13:03:42.789 - info: host.iobroker iobroker Update "system.adapter.wolf-smartset.0"
2023-10-20 13:03:42.791 - info: host.iobroker stopInstance system.adapter.wolf-smartset.0 (force=false, process=true)
2023-10-20 13:03:42.810 - info: host.iobroker iobroker upload [4] wolf-smartset.admin /opt/iobroker/node_modules/iobroker.wolf-smartset/admin/admin.d.ts admin.d.ts video/mp2t
2023-10-20 13:03:42.813 - info: host.iobroker iobroker upload [3] wolf-smartset.admin /opt/iobroker/node_modules/iobroker.wolf-smartset/admin/index_m.html index_m.html text/html
2023-10-20 13:03:42.814 - info: host.iobroker stopInstance system.adapter.wolf-smartset.0 send kill signal
2023-10-20 13:03:42.815 - info: host.iobroker iobroker upload [2] wolf-smartset.admin /opt/iobroker/node_modules/iobroker.wolf-smartset/admin/style.css style.css text/css
2023-10-20 13:03:42.816 - info: host.iobroker iobroker upload [1] wolf-smartset.admin /opt/iobroker/node_modules/iobroker.wolf-smartset/admin/wolf-smartset.png wolf-smartset.png image/png
2023-10-20 13:03:42.818 - info: host.iobroker iobroker upload [0] wolf-smartset.admin /opt/iobroker/node_modules/iobroker.wolf-smartset/admin/words.js words.js application/javascript
2023-10-20 13:03:43.317 - info: host.iobroker instance system.adapter.wolf-smartset.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2023-10-20 13:03:43.826 - info: host.iobroker iobroker exit 0
2023-10-20 13:03:45.846 - info: host.iobroker instance system.adapter.wolf-smartset.0 started with pid 314432
2023-10-20 13:03:46.247 - error: wolf-smartset.0 (314432) Please configure user, password and device in config
2023-10-20 13:04:33.600 - info: host.iobroker stopInstance system.adapter.wolf-smartset.0 (force=false, process=true)
2023-10-20 13:04:33.644 - info: host.iobroker stopInstance system.adapter.wolf-smartset.0 send kill signal
2023-10-20 13:04:34.125 - info: host.iobroker instance system.adapter.wolf-smartset.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2023-10-20 13:04:36.673 - info: host.iobroker instance system.adapter.wolf-smartset.0 started with pid 314485

2023-10-20 13:04:47.301 - info: host.iobroker iobroker upgrade wolf-smartset@1.1.1 --debug
2023-10-20 13:04:47.755 - info: host.iobroker iobroker Update wolf-smartset from @1.0.0 to @1.1.1
2023-10-20 13:04:47.911 - info: host.iobroker iobroker NPM version: 10.2.0
2023-10-20 13:04:47.911 - info: host.iobroker iobroker Installing iobroker.wolf-smartset@1.1.1... (System call)
2023-10-20 13:04:48.965 - info: host.iobroker iobroker added 3 packages, removed 1 package, and changed 1 package in 911ms
2023-10-20 13:04:48.966 - info: host.iobroker iobroker 243 packages are looking for funding run `npm fund` for details
2023-10-20 13:04:49.003 - info: host.iobroker iobroker Update "system.adapter.wolf-smartset.0"
2023-10-20 13:04:49.006 - info: host.iobroker stopInstance system.adapter.wolf-smartset.0 (force=false, process=true)
2023-10-20 13:04:49.041 - info: host.iobroker iobroker upload [4] wolf-smartset.admin /opt/iobroker/node_modules/iobroker.wolf-smartset/admin/admin.d.ts admin.d.ts video/mp2t
2023-10-20 13:04:49.045 - info: host.iobroker iobroker upload [3] wolf-smartset.admin /opt/iobroker/node_modules/iobroker.wolf-smartset/admin/index_m.html index_m.html text/html
2023-10-20 13:04:49.046 - info: host.iobroker stopInstance system.adapter.wolf-smartset.0 send kill signal
2023-10-20 13:04:49.048 - info: host.iobroker iobroker upload [2] wolf-smartset.admin /opt/iobroker/node_modules/iobroker.wolf-smartset/admin/style.css style.css text/css
2023-10-20 13:04:49.049 - info: host.iobroker iobroker upload [1] wolf-smartset.admin /opt/iobroker/node_modules/iobroker.wolf-smartset/admin/wolf-smartset.png wolf-smartset.png image/png
2023-10-20 13:04:49.050 - info: host.iobroker iobroker upload [0] wolf-smartset.admin /opt/iobroker/node_modules/iobroker.wolf-smartset/admin/words.js words.js application/javascript
2023-10-20 13:04:49.539 - info: host.iobroker instance system.adapter.wolf-smartset.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2023-10-20 13:04:50.059 - info: host.iobroker iobroker exit 0
2023-10-20 13:04:52.075 - info: host.iobroker instance system.adapter.wolf-smartset.0 started with pid 314534

2023-10-20 13:04:52.795 - warn: wolf-smartset.0 (314534) API REFRESH TOKEN ERROR: login_required: undefined
2023-10-20 13:04:52.797 - warn: wolf-smartset.0 (314534) Error: login_required: undefined
at WolfSmartSet._refresh (/opt/iobroker/node_modules/iobroker.wolf-smartset/lib/wss.js:454:11)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at WolfSmartSet.openIdInit (/opt/iobroker/node_modules/iobroker.wolf-smartset/lib/wss.js:82:6)
at WolfSmartset.onReady (/opt/iobroker/node_modules/iobroker.wolf-smartset/main.js:46:5)

**Versions:**  
 - Adapter version: 1.1.1
 - JS-Controller version: 5.0.14
 - Node version: 18.17.1
 - Operating system: Ubuntu 22.04.3 LTS

**Comment by Klaus-Lucas** [comment]
Habe ein Testsystem mit dem Repo "Stable" hochgezogen. Da läuft es ohne Probleme.
Versions:

- Adapter version: 1.1.1
- Admin: 6.12.0
- JS-Controller version: 5.0.12
- Node version: 18.17.1
- NPM: 9.6.7
- Operating system: Ubuntu 22.04.3 LTS
