### ISSUE TITLE
 API REFRESH TOKEN ERROR: login_required: undefined

### ISSUE THREAD

**Issue by Klaus-Lucas** [iobroker-community-adapters/ioBroker.wolf-smartset#302]
@Apollon77 
Bekomme bei einem Abfrageintervall von 60 Sek. in reglemäßigen Abständen (10 Std.) diese Meldungen:

2023-10-31 05:55:15.252 - warn: wolf-smartset.0 (2142) API REFRESH TOKEN ERROR: login_required: undefined
2023-10-31 05:55:15.254 - warn: wolf-smartset.0 (2142) Error: login_required: undefined
at WolfSmartSet._refresh (/opt/iobroker/node_modules/iobroker.wolf-smartset/lib/wss.js:454:11)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-31 05:55:15.689 - warn: wolf-smartset.0 (2142) API GET VAL LIST ERROR: Request failed with status code 401

2023-10-31 15:55:20.307 - warn: wolf-smartset.0 (2142) API REFRESH TOKEN ERROR: login_required: undefined
2023-10-31 15:55:20.309 - warn: wolf-smartset.0 (2142) Error: login_required: undefined
at WolfSmartSet._refresh (/opt/iobroker/node_modules/iobroker.wolf-smartset/lib/wss.js:454:11)
at processTicksAndRejections (node:internal/process/task_queues:95:5)

2023-11-01 01:55:24.765 - warn: wolf-smartset.0 (2142) API REFRESH TOKEN ERROR: login_required: undefined
2023-11-01 01:55:24.768 - warn: wolf-smartset.0 (2142) Error: login_required: undefined
at WolfSmartSet._refresh (/opt/iobroker/node_modules/iobroker.wolf-smartset/lib/wss.js:454:11)
at processTicksAndRejections (node:internal/process/task_queues:95:5)

2023-11-01 11:55:28.919 - warn: wolf-smartset.0 (2142) API REFRESH TOKEN ERROR: login_required: undefined
2023-11-01 11:55:28.920 - warn: wolf-smartset.0 (2142) Error: login_required: undefined
at WolfSmartSet._refresh (/opt/iobroker/node_modules/iobroker.wolf-smartset/lib/wss.js:454:11)

**Abfrageintervall von 60 auf 600 Sek. geändert.**

2023-11-02 08:12:14.948 - warn: wolf-smartset.0 (558453) API REFRESH TOKEN ERROR: login_required: undefined
2023-11-02 08:12:14.951 - warn: wolf-smartset.0 (558453) Error: login_required: undefined
at WolfSmartSet._refresh (/opt/iobroker/node_modules/iobroker.wolf-smartset/lib/wss.js:454:11)
at processTicksAndRejections (node:internal/process/task_queues:95:5)

2023-11-03 04:12:24.156 - warn: wolf-smartset.0 (558453) API REFRESH TOKEN ERROR: login_required: undefined
2023-11-03 04:12:24.158 - warn: wolf-smartset.0 (558453) Error: login_required: undefined
at WolfSmartSet._refresh (/opt/iobroker/node_modules/iobroker.wolf-smartset/lib/wss.js:454:11)
at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Versions:**  
 - Adapter version: 1.1.1
 - Admin: 6.12.2
 - JS-Controller version: 5.0.16
 - Node version: 18.17.1
 - NPM: 10.2.0
 - Operating system: Ubuntu 22.04.3 LTS

**Additional context**

**Comment by mcm1957** [comment]
Please retest with 2.0.0

**Comment by Klaus-Lucas** [comment]
Bekomme auch mit dieser Version weiterhin
``
wolf-smartset.0 | 2025-04-04 07:37:48.365 | warn | _refreshAuthToken(): ERROR: login_required / undefined
``

Beim Adapterstart:
``
2025-04-03 13:29:39.222 - warn: wolf-smartset.0 (332811) State "wolf-smartset.0.Fachmann.Bedienmodul_BM-2 0.Parameter.412_Anlagenparameter.22002300000" has no existing object, this might lead to an error in future versions
2025-04-03 13:29:39.223 - warn: wolf-smartset.0 (332811) State "wolf-smartset.0.Fachmann.Bedienmodul_BM-2 0.Parameter.412_Anlagenparameter.22010400000" has no existing object, this might lead to an error in future versions
2025-04-03 13:29:39.224 - warn: wolf-smartset.0 (332811) State "wolf-smartset.0.Fachmann.Bedienmodul_BM-2 0.Parameter.412_Anlagenparameter.22002500000" has no existing object, this might lead to an error in future versions
2025-04-03 13:29:39.224 - warn: wolf-smartset.0 (332811) State "wolf-smartset.0.Fachmann.Bedienmodul_BM-2 0.Parameter.412_Anlagenparameter.22002600000" has no existing object, this might lead to an error in future versions
2025-04-03 13:29:39.224 - warn: wolf-smartset.0 (332811) State "wolf-smartset.0.Fachmann.Bedienmodul_BM-2 0.Parameter.412_Anlagenparameter.22002700000" has no existing object, this might lead to an error in future versions
2025-04-03 13:29:39.224 - warn: wolf-smartset.0 (332811) State "wolf-smartset.0.Fachmann.Bedienmodul_BM-2 0.Parameter.412_Anlagenparameter.22002800000" has no existing object, this might lead to an error in future versions
2025-04-03 13:29:39.224 - warn: wolf-smartset.0 (332811) State "wolf-smartset.0.Fachmann.Bedienmodul_BM-2 0.Parameter.412_Anlagenparameter.22012600000" has no existing object, this might lead to an error in future versions
2025-04-03 13:29:39.224 - warn: wolf-smartset.0 (332811) State "wolf-smartset.0.Fachmann.Bedienmodul_BM-2 0.Parameter.412_Anlagenparameter.22012700000" has no existing object, this might lead to an error in future versions
2025-04-03 13:29:39.224 - warn: wolf-smartset.0 (332811) State "wolf-smartset.0.Fachmann.Bedienmodul_BM-2 0.Parameter.412_Anlagenparameter.22002900000" has no existing object, this might lead to an error in future versions
2025-04-03 13:29:39.224 - warn: wolf-smartset.0 (332811) State "wolf-smartset.0.Fachmann.Bedienmodul_BM-2 0.Parameter.412_Anlagenparameter.22003000000" has no existing object, this might lead to an error in future versions
2025-04-03 13:29:39.224 - warn: wolf-smartset.0 (332811) State "wolf-smartset.0.Fachmann.Bedienmodul_BM-2 0.Parameter.412_Anlagenparameter.22003100000" has no existing object, this might lead to an error in future versions
2025-04-03 13:29:39.224 - warn: wolf-smartset.0 (332811) State "wolf-smartset.0.Fachmann.Bedienmodul_BM-2 0.Parameter.412_Anlagenparameter.22010800000" has no existing object, this might lead to an error in future versions
2025-04-03 13:29:39.225 - warn: wolf-smartset.0 (332811) State "wolf-smartset.0.Fachmann.Bedienmodul_BM-2 0.Parameter.412_Anlagenparameter.22009500000" has no existing object, this might lead to an error in future versions
``

**Comment by mcm1957** [comment]
@flingo64 ne Idee dazu?

**Comment by flingo64** [comment]
`wolf-smartset.0 | 2025-04-04 07:37:48.365 | warn | _refreshAuthToken(): ERROR: login_required / undefined`
ist kein Bug, sondern nur der Hinweis, dass der Adapter jetzt eine Re-authentisierung ausführen muss, entsprechende info logs sollten dann folgen:
```
...
info: wolf-smartset.0 (16862) Initialization with Login and new Session done!

```

`...  has no existing object`
Werden die o.g. Objekte angelegt? Gibt es Objekte mit der Beschreibung 'obsoleted'? Falls es obsoleted objects gibt (das sind Objekte, die mit diesem Pfad nicht mehr von der Wolf Smartset API gemeldet werden), dann mal die entsprechenden Unterbäume komplett löschen und den Adapter danach neu starten. Wurde der ganze Baum `wolf-smartset.0.Fachmann.Bedienmodul_BM-2 0.Parameter.412_Anlagenparameter` nicht angelegt, hilft nur mal auf Debug zu schalten, dann muss man sich die komplette Initialisierung anschauen.

Und gerne nochmal auf dem Wolf Smartset Portal kontrollieren, ob der benutzte Account auch die Zugriffsrechte 'Fachmann schreiben' hat.

![Image](https://github.com/user-attachments/assets/a9f7c212-1fd2-44d1-a994-d39284ec1159)

**Comment by Klaus-Lucas** [comment]
Die 412er Parameter wurden angelegt und befüllt.
![Image](https://github.com/user-attachments/assets/d00201aa-792c-478a-9b85-6def432e9c64)

![Image](https://github.com/user-attachments/assets/4ab2240a-bcfa-4e3c-815c-f92954481a2c)

Fehermeldung kommt daher auch nicht nach einem erneuten Start.

Das eine Re-authentisierung als Warn/Error gekennzeichnet werden muss, halte ich persönlich für nicht notwendig, da es sich um einen normalen Vorgang handelt. INFO fände ich besser.

Account ist ok

2025-04-04 18:43:07.974 - info: wolf-smartset.0 (59329) Initialization with Login and new Session done!
2025-04-04 18:43:08.000 - debug: wolf-smartset.0 (59329) API EXPERT LOGIN: 200
2025-04-04 18:43:08.000 - info: wolf-smartset.0 (59329) Expert Login done!
2025-04-04 18:43:08.000 - debug: wolf-smartset.0 (59329) Setting up re-init for Expert Login

Denke also, dass der initial gemeldete Fehler behoben wurde.
Danke für die Arbeit.
